services:
  - type: web
    name: reniec
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: DB_URL
        value: jdbc:mysql://database-zegel.cbo8w4ekwbz1.sa-east-1.rds.amazonaws.com:3306/reniec
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: ZEGEL12345!